# Generated by Django 4.1.3 on 2022-12-03 00:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='created_date',
            field=models.TextField(default=datetime.datetime(2022, 12, 3, 0, 36, 52, 313410, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='course',
            name='created_date',
            field=models.TextField(default=datetime.datetime(2022, 12, 3, 0, 36, 52, 313410, tzinfo=datetime.timezone.utc)),
        ),
    ]
