# Generated by Django 4.1.3 on 2022-12-03 02:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_alter_class_created_date_alter_course_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='created_date',
            field=models.TextField(default=datetime.datetime(2022, 12, 3, 2, 7, 56, 286215, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='course',
            name='created_date',
            field=models.TextField(default=datetime.datetime(2022, 12, 3, 2, 7, 56, 286215, tzinfo=datetime.timezone.utc)),
        ),
    ]
