# Generated by Django 4.1.3 on 2022-12-03 03:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_course_course_description_alter_class_created_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2022, 12, 3, 3, 12, 56, 135026, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='course',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2022, 12, 3, 3, 12, 56, 135026, tzinfo=datetime.timezone.utc)),
        ),
    ]
