# Generated by Django 4.1.3 on 2022-12-02 22:04

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('description', models.TextField()),
                ('created_date', models.TimeField(default=datetime.datetime(2022, 12, 2, 22, 4, 49, 117412, tzinfo=datetime.timezone.utc))),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_id', models.CharField(max_length=32)),
                ('date_joined', models.TimeField()),
                ('created_date', models.TimeField(default=datetime.datetime(2022, 12, 2, 22, 4, 49, 118410, tzinfo=datetime.timezone.utc))),
                ('is_principle', models.BooleanField(default=False)),
                ('position', models.ManyToManyField(to='stakeholder.position')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=32)),
                ('created_date', models.TimeField(default=datetime.datetime(2022, 12, 2, 22, 4, 49, 117412, tzinfo=datetime.timezone.utc))),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.TimeField(default=datetime.datetime(2022, 12, 2, 22, 4, 49, 118410, tzinfo=datetime.timezone.utc))),
                ('children', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stakeholder.student')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Administrator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.TimeField(default=datetime.datetime(2022, 12, 2, 22, 4, 49, 119410, tzinfo=datetime.timezone.utc))),
                ('position', models.ManyToManyField(to='stakeholder.position')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
