# Generated by Django 4.1.3 on 2022-12-02 22:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
        ('stakeholder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='enroll_courses',
            field=models.ManyToManyField(to='course.class'),
        ),
        migrations.AlterField(
            model_name='administrator',
            name='created_date',
            field=models.TimeField(default=datetime.datetime(2022, 12, 2, 22, 52, 45, 614844, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='parent',
            name='created_date',
            field=models.TimeField(default=datetime.datetime(2022, 12, 2, 22, 52, 45, 614844, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='position',
            name='created_date',
            field=models.TimeField(default=datetime.datetime(2022, 12, 2, 22, 52, 45, 613862, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='student',
            name='created_date',
            field=models.TimeField(default=datetime.datetime(2022, 12, 2, 22, 52, 45, 613862, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='created_date',
            field=models.TimeField(default=datetime.datetime(2022, 12, 2, 22, 52, 45, 614844, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='date_joined',
            field=models.TimeField(blank=True),
        ),
    ]
