# Generated by Django 4.1.3 on 2022-12-03 00:36

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stakeholder', '0002_student_enroll_courses_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrator',
            name='created_date',
            field=models.TimeField(default=datetime.datetime(2022, 12, 3, 0, 36, 52, 315423, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='parent',
            name='created_date',
            field=models.TimeField(default=datetime.datetime(2022, 12, 3, 0, 36, 52, 315423, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='position',
            name='created_date',
            field=models.TimeField(default=datetime.datetime(2022, 12, 3, 0, 36, 52, 313410, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='student',
            name='created_date',
            field=models.TimeField(default=datetime.datetime(2022, 12, 3, 0, 36, 52, 313410, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='student',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='created_date',
            field=models.TimeField(default=datetime.datetime(2022, 12, 3, 0, 36, 52, 314410, tzinfo=datetime.timezone.utc)),
        ),
    ]
