# Generated by Django 4.1.3 on 2022-12-03 00:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stakeholder', '0003_alter_administrator_created_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='administrator',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='parent',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='student',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='created_date',
        ),
        migrations.AlterField(
            model_name='position',
            name='created_date',
            field=models.TimeField(default=datetime.datetime(2022, 12, 3, 0, 58, 40, 993522, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='date_joined',
            field=models.DateField(blank=True),
        ),
    ]
