# Generated by Django 4.1.3 on 2022-12-03 02:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stakeholder', '0004_remove_administrator_created_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='father_name',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='mother_name',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='phone_number',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AlterField(
            model_name='position',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2022, 12, 3, 2, 7, 56, 286215, tzinfo=datetime.timezone.utc)),
        ),
    ]
