# Generated by Django 4.1.3 on 2022-12-03 03:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stakeholder', '0005_student_father_name_student_mother_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2022, 12, 3, 3, 9, 32, 522358, tzinfo=datetime.timezone.utc)),
        ),
    ]
