# Generated by Django 4.1.3 on 2022-12-03 03:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stakeholder', '0006_alter_position_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2022, 12, 3, 3, 12, 56, 135026, tzinfo=datetime.timezone.utc)),
        ),
    ]
