# Generated by Django 4.1.3 on 2022-12-19 21:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stakeholder', '0009_alter_position_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='level',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='position',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2022, 12, 19, 21, 44, 46, 363892, tzinfo=datetime.timezone.utc)),
        ),
    ]
