# Generated by Django 4.1.3 on 2022-12-19 21:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stakeholder', '0010_student_level_alter_position_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2022, 12, 19, 21, 58, 32, 713716, tzinfo=datetime.timezone.utc)),
        ),
    ]
