# Generated by Django 4.1.3 on 2022-12-19 22:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stakeholder', '0011_alter_position_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2022, 12, 19, 22, 1, 56, 20755, tzinfo=datetime.timezone.utc)),
        ),
    ]
