# Generated by Django 4.1.3 on 2022-12-20 12:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stakeholder', '0012_alter_position_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2022, 12, 20, 12, 26, 25, 743218, tzinfo=datetime.timezone.utc)),
        ),
    ]
